### ISSUE TITLE
Failure executing javac

### ISSUE THREAD

**Issue by maxenceboucas** [OgarProject/Ogar2-Server#14]
Hi 

i was falling the installation of #11 

Fist, i had a problem with java on maven (jdk or jre) i solved it.

But now i have that error :

```
Failure executing javac, but could not parse the error:
 [ERROR] javac: invalid target release: 1.8
 [ERROR] Usage: javac <options> <source files>
 [ERROR] use -help for a list of possible options
 [ERROR] -> [Help 1]
 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal         org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project ogar-  api: Compilation failure
 Failure executing javac, but could not parse the error:
 javac: invalid target release: 1.8
 Usage: javac <options> <source files>
 use -help for a list of possible options
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
 Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
 Failure executing javac, but could not parse the error:
  javac: invalid target release: 1.8
 Usage: javac <options> <source files>
 use -help for a list of possible options


at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
  [ERROR] 
  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
  [ERROR] 
  [ERROR] For more information about the errors and possible solutions, please read the following articles:
  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Thanks for help

**Comment by Edgeset** [comment]
Install jdk 1.8

su -
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update
apt-get install oracle-java8-installer

**Comment by elitajmx** [comment]
woooooooooooooooooooooooooot do i need to fucking dooooooooo im not a fucking hacker of command things or what the fuck can someone make a fucking video about this ?

**Comment by Edgeset** [comment]
Install Java, install and compile it with maven or use and IDE with all things you need, run it

**Comment by elitajmx** [comment]
what means compile? can you add me on skype and we do this? thank you
skype: macuhaljaz

**Comment by ThunderGemios10** [comment]
@elitajmx Just download my compiled build on my jenkins server: http://ci.thundergemios10.com/job/Ogar2-Server/

**Comment by Mistik** [comment]
> @elitajmx Just download my compiled build on my jenkins server: http://ci.thundergemios10.com/job/Ogar2-Server/

Says not found
