### ISSUE TITLE
Problem at the exection of ogar-server-2.0-SNAP...

### ISSUE THREAD

**Issue by B14CKr4V3N** [OgarProject/Ogar2-Server#35]
Hello,
When I execute this command : `java -jar target/ogar-server-2.0-SNAPSHOT.jar`
I have this error : 
`
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/ogarproject/ogar/server/OgarServer : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
`

**Comment by ItzLevvie** [comment]
Use https://github.com/Barbosik/MultiOgar, **Ogar2** isn't fully finished and therefore will have some bugs.
